### ISSUE TITLE
Task List for week 6

### ISSUE THREAD

**Issue by mayinot** [PERSONALISED-CONCIERGE/SIT_ICT2106_p3-M2#18]
Assigned: May Madi Aung 
Due date: 16 Feb 2021
- [ ]  2106 Report
    - [ ]  Revise all use case description
        - [ ]  UC7 & UC3
    - [ ]  Layered Architecture - May
    - [ ]  Component diagram explanation - May
    - [ ]  All sequence diagram explanation
        - [ ]  UC7 & UC3
    - [ ]  Architecture design principle
        - [ ]  Coupling - May
        - [ ]  Cohesion - May
    - [ ]  Software Design Evaluation
- [ ]  2106 Coding
    - [ ]  Code Model and domain logic for Transportation
        - [ ]  viewing transportation (user)
        - [ ]  adding/editing transportation (admin)
- [ ]  2106 Diagram
    - [ ]  Revise Architecture diagram
    - [ ]  Revise component diagram
- [ ]  Prepare demo flow and timing with other module

**Comment by mayinot** [comment]
![image](https://user-images.githubusercontent.com/31657679/154701274-4677062f-df94-4ebe-a536-6a17dac014a5.png)
![image](https://user-images.githubusercontent.com/31657679/154701361-3660628a-ea27-4a26-9365-b117881f4dc9.png)

Finished the diagram and the prototype was demo to client and Client agreement was gathered
